//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.0
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by wsdl, Version=4.0.30319.33440.
// 
namespace FP.Spartakiade2015.WebservicePersistence.TestConsole
{
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BookCapacity_Binding", Namespace="http://www.pommerening-online.de/wsdl/EnergyService/")]
    public partial class BookCapacityService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback BookCapacityOperationCompleted;
        
        /// <remarks/>
        public BookCapacityService() {
            this.Url = "http://www.pommerening-online.de/API/BookCapacityService.asmx";
        }
        
        /// <remarks/>
        public event BookCapacityCompletedEventHandler BookCapacityCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.pommerening-online.de/wsdl/EnergyService/BookCapacity", RequestElementName="BookCapacityRequest", RequestNamespace="http://www.pommerening-online.de/wsdl/EnergyService/", ResponseNamespace="http://www.pommerening-online.de/wsdl/EnergyService/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("request")]
        public BookCapacityResponseType BookCapacity(BookCapacityRequestType request) {
            object[] results = this.Invoke("BookCapacity", new object[] {
                        request});
            return ((BookCapacityResponseType)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginBookCapacity(BookCapacityRequestType request, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("BookCapacity", new object[] {
                        request}, callback, asyncState);
        }
        
        /// <remarks/>
        public BookCapacityResponseType EndBookCapacity(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((BookCapacityResponseType)(results[0]));
        }
        
        /// <remarks/>
        public void BookCapacityAsync(BookCapacityRequestType request) {
            this.BookCapacityAsync(request, null);
        }
        
        /// <remarks/>
        public void BookCapacityAsync(BookCapacityRequestType request, object userState) {
            if ((this.BookCapacityOperationCompleted == null)) {
                this.BookCapacityOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBookCapacityOperationCompleted);
            }
            this.InvokeAsync("BookCapacity", new object[] {
                        request}, this.BookCapacityOperationCompleted, userState);
        }
        
        private void OnBookCapacityOperationCompleted(object arg) {
            if ((this.BookCapacityCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BookCapacityCompleted(this, new BookCapacityCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.pommerening-online.de/wsdl/EnergyService/")]
    public partial class BookCapacityRequestType {
        
        private string messageIdentifierField;
        
        private string customerField;
        
        private decimal quantityField;
        
        private System.DateTime validFromField;
        
        private System.DateTime validToField;
        
        private CapacityUnit unitField;
        
        /// <remarks/>
        public string MessageIdentifier {
            get {
                return this.messageIdentifierField;
            }
            set {
                this.messageIdentifierField = value;
            }
        }
        
        /// <remarks/>
        public string Customer {
            get {
                return this.customerField;
            }
            set {
                this.customerField = value;
            }
        }
        
        /// <remarks/>
        public decimal Quantity {
            get {
                return this.quantityField;
            }
            set {
                this.quantityField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime ValidFrom {
            get {
                return this.validFromField;
            }
            set {
                this.validFromField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime ValidTo {
            get {
                return this.validToField;
            }
            set {
                this.validToField = value;
            }
        }
        
        /// <remarks/>
        public CapacityUnit Unit {
            get {
                return this.unitField;
            }
            set {
                this.unitField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.pommerening-online.de/wsdl/EnergyService/")]
    public enum CapacityUnit {
        
        /// <remarks/>
        MWh,
        
        /// <remarks/>
        KWh,
        
        /// <remarks/>
        GWh,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.pommerening-online.de/wsdl/EnergyService/")]
    public partial class BookCapacityResponseType {
        
        private string messageIdentifierField;
        
        private CapacityUnit unitField;
        
        private decimal quantityField;
        
        /// <remarks/>
        public string MessageIdentifier {
            get {
                return this.messageIdentifierField;
            }
            set {
                this.messageIdentifierField = value;
            }
        }
        
        /// <remarks/>
        public CapacityUnit Unit {
            get {
                return this.unitField;
            }
            set {
                this.unitField = value;
            }
        }
        
        /// <remarks/>
        public decimal Quantity {
            get {
                return this.quantityField;
            }
            set {
                this.quantityField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
    public delegate void BookCapacityCompletedEventHandler(object sender, BookCapacityCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BookCapacityCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BookCapacityCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public BookCapacityResponseType Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((BookCapacityResponseType)(this.results[0]));
            }
        }
    }
}
